### ISSUE TITLE
can help on this project...

### ISSUE THREAD

**Issue by arif-hanif** [ladybug-tools/spider-react#5]
i am up for helping out on this project... let me know if there is a piece i can help out on.

**Comment by arif-hanif** [comment]
maybe if we can make a road map...

**Comment by AntoineDao** [comment]
Hi! Great, this repo is super new and for the moment mainly aims to reproduce features already achieved in the [vanilla html/javascript spider repo](https://www.ladybug.tools/spider-gbxml-tools/spider-gbxml-viewer/r15/spider-gbxml-viewer15.html#https://www.ladybug.tools/spider/gbxml-sample-files/bristol-clifton-downs-fixed.xml). I'm probably going to have a catch up with @theo-armour at some point this week or the next to see what's worth doing and how much time anyone can dedicate to any of this. Easiest place to discuss none code specific related issues is probably the lb-tools forum for now. Mind setting up an account and starting a conversation [there](https://discourse.ladybug.tools/)? This will ensure more people can see what work is being proposed and such. Thanks again for the interest 😄
